name: Build Test

on:
  push:
    # Don't run for tags
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '*'

jobs:
  build-webos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Compactor
        run: |
          sudo wget https://github.com/mateussouzaweb/compactor/releases/download/latest/compactor -O /usr/local/bin/compactor
          sudo chmod +x /usr/local/bin/compactor

      - name: Install NPM packages
        run: |
          sudo npm install
          sudo npm install --global rollup

      - name: Build TV package
        run: |
          npm run build
          npm run bundle
          npm run app-package
          npm run app-manifest

      - uses: actions/upload-artifact@v2
        with:
          name: webos-snapshot
          path: |
            bin/*.ipk
            bin/webosbrew.manifest.json
