name: Build Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  build-webos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          curl https://mateussouzaweb.github.io/compactor/install.sh | bash
          npm install
          npm install --global rollup

      - name: Build package
        run: |
          npm run build
          npm run app-package
          npm run app-manifest

      - name: Create release
        id: create_release_webos
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tagName.outputs.tag }}
          prerelease: false
          allowUpdates: true
          artifacts: bin/*.ipk,bin/webosbrew.manifest.json