name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  build-webos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install webOS CLI
        run: |
          sudo npm install -g @webosose/ares-cli

      - name: Install compactor
        run: |
          sudo wget https://raw.githubusercontent.com/mateussouzaweb/compactor/master/bin/compactor -O /usr/local/bin/compactor
          sudo chmod +x /usr/local/bin/compactor

      - name: Install webosbrew publish tools
        run: |
          sudo npm install -g @webosbrew/pub-utils

      - name: Build package
        run: |
          make build
          make app_build
          webosbrew-gen-manifest -a src/appinfo.json -p bin/*.ipk -o bin/webosbrew.manifest.json \
            -i https://raw.githubusercontent.com/mateussouzaweb/crunchyroll-webos/master/src/img/80px.png \
            -l https://github.com/mateussouzaweb/crunchyroll-webos

      - name: Create Release
        id: create_release_webos
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tagName.outputs.tag }}
          prerelease: false
          allowUpdates: true
          artifacts: bin/*.ipk,bin/webosbrew.manifest.json